PACKAGES := signaling summoners
APP_MAIN := server.go
APP_NAME := server

NO_COLOR=\033[0m
OK_COLOR=\033[32;01m
ERROR_COLOR=\033[31;01m
WARN_COLOR=\033[33;01m

VERSION = $(shell git log --pretty=format:'%h:%s' -n 1 | tr -s ' ' | tr ' ' '_')
